WIP : Add templates for almalinux 8 and debian 11
xcp-ng-rpms/guest-templates-json pull request #1
Opened 2021-11-22 10:52 UTC by gduperrey

Adding two templates for AlmaLinux 8 and Debian 11.

2021-11-22 13:32 UTC, stormi requested changes

2021-11-22 13:32 UTC, stormi commented on SPECS/guest-templates-json.spec
> +- Add template for AlmaLinux 8 and Debian 11 Bulleyes
```suggestion
- Add template for AlmaLinux 8 and Debian 11 Bullseye

```

2021-11-22 13:32 UTC, stormi commented on SPECS/guest-templates-json.spec
> +#XCP-ng patches
```suggestion
# XCP-ng patches
```

2021-11-22 13:33 UTC, stormi commented
The target branch for the PR should be 8.2 as this is meant to be an update to the stable release of XCP-ng.

2021-11-23 14:29 UTC, gduperrey commented
[build koji ok](https://koji.xcp-ng.org/taskinfo?taskID=20566)

2021-11-23 14:39 UTC, merged